services:
  e2e:
    # 1. O build (do Dockerfile) cria a imagem E roda o build da extensão
    build: .
    image: thi977/focus-tracker-e2e:latest
    environment:
      - CI=true
    volumes:
      # 2. NÃO monte a pasta inteira.
      # Monte APENAS o relatório para que ele saia do contêiner.
      - ./playwright-report:/app/playwright-report
    working_dir: /app

    # 3. O build JÁ FOI FEITO pelo Dockerfile. A pasta /app/dist existe.
    #    Rode APENAS os testes.
    command: npm run test:e2e

    shm_size: 2gb
